insert into Class (ClassID, Title) values (1, 'cubilia curae nulla');
insert into Class (ClassID, Title) values (2, 'commodo placerat praesent blandit nam nulla integer pede');
insert into Class (ClassID, Title) values (3, 'in magna bibendum imperdiet');
insert into Class (ClassID, Title) values (4, 'varius nulla facilisi cras');
insert into Class (ClassID, Title) values (5, 'sagittis sapien cum');
insert into Class (ClassID, Title) values (6, 'sapien');
insert into Class (ClassID, Title) values (7, 'magna vulputate');
insert into Class (ClassID, Title) values (8, 'magna vulputate luctus cum sociis natoque penatibus');
insert into Class (ClassID, Title) values (9, 'ut');
insert into Class (ClassID, Title) values (10, 'magna at nunc commodo');
insert into Class (ClassID, Title) values (11, 'at');
insert into Class (ClassID, Title) values (12, 'nullam varius nulla facilisi cras non velit nec nisi vulputate');
insert into Class (ClassID, Title) values (13, 'lectus pellentesque at nulla suspendisse potenti cras in purus eu');
insert into Class (ClassID, Title) values (14, 'eros');
insert into Class (ClassID, Title) values (15, 'mattis egestas metus aenean fermentum donec ut');
insert into Class (ClassID, Title) values (16, 'porttitor lacus at turpis');
insert into Class (ClassID, Title) values (17, 'pellentesque volutpat dui maecenas');
insert into Class (ClassID, Title) values (18, 'vitae quam suspendisse');
insert into Class (ClassID, Title) values (19, 'nunc rhoncus dui vel sem sed sagittis');
insert into Class (ClassID, Title) values (20, 'nulla neque libero');
insert into Class (ClassID, Title) values (21, 'pede morbi porttitor');
insert into Class (ClassID, Title) values (22, 'aliquet maecenas leo odio condimentum id luctus nec');
insert into Class (ClassID, Title) values (23, 'et magnis dis parturient');
insert into Class (ClassID, Title) values (24, 'mi pede malesuada in imperdiet et commodo');
insert into Class (ClassID, Title) values (25, 'convallis nunc proin');
insert into Class (ClassID, Title) values (26, 'non interdum in ante vestibulum ante');
insert into Class (ClassID, Title) values (27, 'aenean sit amet justo');
insert into Class (ClassID, Title) values (28, 'purus sit amet nulla quisque arcu libero rutrum ac');
insert into Class (ClassID, Title) values (29, 'eu orci');
insert into Class (ClassID, Title) values (30, 'id pretium iaculis diam erat fermentum justo nec');
insert into Class (ClassID, Title) values (31, 'etiam');
insert into Class (ClassID, Title) values (32, 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus');
insert into Class (ClassID, Title) values (33, 'nonummy integer non velit donec diam');
insert into Class (ClassID, Title) values (34, 'interdum mauris non ligula pellentesque');
insert into Class (ClassID, Title) values (35, 'felis eu sapien cursus');
insert into Class (ClassID, Title) values (36, 'mus vivamus vestibulum sagittis sapien cum sociis');
insert into Class (ClassID, Title) values (37, 'phasellus in felis donec semper sapien a libero');
insert into Class (ClassID, Title) values (38, 'id pretium iaculis diam erat fermentum justo nec condimentum');
insert into Class (ClassID, Title) values (39, 'feugiat et');
insert into Class (ClassID, Title) values (40, 'erat volutpat in congue etiam justo');
insert into Class (ClassID, Title) values (41, 'turpis');
insert into Class (ClassID, Title) values (42, 'est et tempus semper est quam pharetra');
insert into Class (ClassID, Title) values (43, 'sem fusce consequat nulla nisl');
insert into Class (ClassID, Title) values (44, 'scelerisque mauris sit amet eros suspendisse accumsan');
insert into Class (ClassID, Title) values (45, 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida');
insert into Class (ClassID, Title) values (46, 'eget rutrum at lorem integer tincidunt');
insert into Class (ClassID, Title) values (47, 'curabitur gravida nisi at');
insert into Class (ClassID, Title) values (48, 'morbi vel lectus in quam fringilla');
insert into Class (ClassID, Title) values (49, 'faucibus orci luctus et');
insert into Class (ClassID, Title) values (50, 'faucibus orci luctus et ultrices posuere');
insert into Class (ClassID, Title) values (51, 'nulla sed accumsan felis ut');
insert into Class (ClassID, Title) values (52, 'sem fusce consequat');
insert into Class (ClassID, Title) values (53, 'molestie hendrerit at');
insert into Class (ClassID, Title) values (54, 'sit amet sapien dignissim vestibulum');
insert into Class (ClassID, Title) values (55, 'eget eros elementum pellentesque quisque porta volutpat erat');
insert into Class (ClassID, Title) values (56, 'mi sit amet lobortis sapien sapien');
insert into Class (ClassID, Title) values (57, 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus');
insert into Class (ClassID, Title) values (58, 'amet');
insert into Class (ClassID, Title) values (59, 'nullam');
insert into Class (ClassID, Title) values (60, 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit');
insert into Class (ClassID, Title) values (61, 'ipsum praesent blandit lacinia erat');
insert into Class (ClassID, Title) values (62, 'congue diam id ornare imperdiet sapien urna pretium nisl');
insert into Class (ClassID, Title) values (63, 'ante ipsum primis in faucibus orci luctus');
insert into Class (ClassID, Title) values (64, 'ullamcorper purus');
insert into Class (ClassID, Title) values (65, 'libero non');
insert into Class (ClassID, Title) values (66, 'eget rutrum at lorem integer');
insert into Class (ClassID, Title) values (67, 'porta volutpat erat quisque erat eros viverra');
insert into Class (ClassID, Title) values (68, 'in lectus pellentesque at nulla suspendisse potenti cras in purus');
insert into Class (ClassID, Title) values (69, 'sit amet cursus id turpis integer aliquet massa id');
insert into Class (ClassID, Title) values (70, 'praesent id');
