insert into UserGroup (GroupID, GroupName, CreatorID) values (1, 'montes nascetur ridiculus', 4);
insert into UserGroup (GroupID, GroupName, CreatorID) values (2, 'donec pharetra magna', 2);
insert into UserGroup (GroupID, GroupName, CreatorID) values (3, 'quam sapien', 28);
insert into UserGroup (GroupID, GroupName, CreatorID) values (4, 'cras pellentesque volutpat', 19);
insert into UserGroup (GroupID, GroupName, CreatorID) values (5, 'volutpat dui maecenas', 34);
insert into UserGroup (GroupID, GroupName, CreatorID) values (6, 'ante', 9);
insert into UserGroup (GroupID, GroupName, CreatorID) values (7, 'rhoncus', 40);
insert into UserGroup (GroupID, GroupName, CreatorID) values (8, 'pede lobortis', 2);
insert into UserGroup (GroupID, GroupName, CreatorID) values (9, 'aliquet', 37);
insert into UserGroup (GroupID, GroupName, CreatorID) values (10, 'condimentum', 32);
insert into UserGroup (GroupID, GroupName, CreatorID) values (11, 'a odio in', 38);
insert into UserGroup (GroupID, GroupName, CreatorID) values (12, 'ornare', 8);
insert into UserGroup (GroupID, GroupName, CreatorID) values (13, 'venenatis', 32);
insert into UserGroup (GroupID, GroupName, CreatorID) values (14, 'eu', 13);
insert into UserGroup (GroupID, GroupName, CreatorID) values (15, 'molestie nibh in', 31);
insert into UserGroup (GroupID, GroupName, CreatorID) values (16, 'est et tempus', 38);
insert into UserGroup (GroupID, GroupName, CreatorID) values (17, 'posuere cubilia', 17);
insert into UserGroup (GroupID, GroupName, CreatorID) values (18, 'donec', 40);
insert into UserGroup (GroupID, GroupName, CreatorID) values (19, 'sagittis sapien', 6);
insert into UserGroup (GroupID, GroupName, CreatorID) values (20, 'a nibh in', 13);
