use taskwiz;

insert into Planner (PlannerID, PlannerName, UserID) values (1, 'placerat praesent blandit', 34);
insert into Planner (PlannerID, PlannerName, UserID) values (2, 'elementum nullam', 34);
insert into Planner (PlannerID, PlannerName, UserID) values (3, 'nec condimentum neque', 19);
insert into Planner (PlannerID, PlannerName, UserID) values (4, 'suspendisse accumsan', 30);
insert into Planner (PlannerID, PlannerName, UserID) values (5, 'neque', 4);
insert into Planner (PlannerID, PlannerName, UserID) values (6, 'tristique', 8);
insert into Planner (PlannerID, PlannerName, UserID) values (7, 'velit nec', 38);
insert into Planner (PlannerID, PlannerName, UserID) values (8, 'sapien sapien', 37);
insert into Planner (PlannerID, PlannerName, UserID) values (9, 'diam in magna', 34);
insert into Planner (PlannerID, PlannerName, UserID) values (10, 'venenatis turpis', 28);
insert into Planner (PlannerID, PlannerName, UserID) values (11, 'faucibus cursus urna', 19);
insert into Planner (PlannerID, PlannerName, UserID) values (12, 'nunc proin', 16);
insert into Planner (PlannerID, PlannerName, UserID) values (13, 'eleifend', 14);
insert into Planner (PlannerID, PlannerName, UserID) values (14, 'duis', 27);
insert into Planner (PlannerID, PlannerName, UserID) values (15, 'erat fermentum', 31);
insert into Planner (PlannerID, PlannerName, UserID) values (16, 'lacus at', 15);
insert into Planner (PlannerID, PlannerName, UserID) values (17, 'quis odio', 33);
insert into Planner (PlannerID, PlannerName, UserID) values (18, 'erat vestibulum sed', 16);
insert into Planner (PlannerID, PlannerName, UserID) values (19, 'nam ultrices libero', 23);
insert into Planner (PlannerID, PlannerName, UserID) values (20, 'blandit', 17);
insert into Planner (PlannerID, PlannerName, UserID) values (21, 'aenean fermentum donec', 7);
insert into Planner (PlannerID, PlannerName, UserID) values (22, 'sit amet cursus', 3);
insert into Planner (PlannerID, PlannerName, UserID) values (23, 'proin', 17);
insert into Planner (PlannerID, PlannerName, UserID) values (24, 'magna bibendum', 24);
insert into Planner (PlannerID, PlannerName, UserID) values (25, 'ridiculus mus', 36);
insert into Planner (PlannerID, PlannerName, UserID) values (26, 'augue luctus tincidunt', 24);
insert into Planner (PlannerID, PlannerName, UserID) values (27, 'scelerisque quam turpis', 30);
insert into Planner (PlannerID, PlannerName, UserID) values (28, 'ut ultrices vel', 12);
insert into Planner (PlannerID, PlannerName, UserID) values (29, 'id consequat in', 24);
insert into Planner (PlannerID, PlannerName, UserID) values (30, 'nulla tempus vivamus', 24);
insert into Planner (PlannerID, PlannerName, UserID) values (31, 'sit', 23);
insert into Planner (PlannerID, PlannerName, UserID) values (32, 'nulla', 16);
insert into Planner (PlannerID, PlannerName, UserID) values (33, 'non mauris', 1);
insert into Planner (PlannerID, PlannerName, UserID) values (34, 'parturient', 17);
insert into Planner (PlannerID, PlannerName, UserID) values (35, 'faucibus orci', 20);
insert into Planner (PlannerID, PlannerName, UserID) values (36, 'amet', 12);
insert into Planner (PlannerID, PlannerName, UserID) values (37, 'sit', 20);
insert into Planner (PlannerID, PlannerName, UserID) values (38, 'nec condimentum', 5);
insert into Planner (PlannerID, PlannerName, UserID) values (39, 'eu orci', 15);
insert into Planner (PlannerID, PlannerName, UserID) values (40, 'scelerisque quam turpis', 21);
insert into Planner (PlannerID, PlannerName, UserID) values (41, 'etiam pretium iaculis', 33);
insert into Planner (PlannerID, PlannerName, UserID) values (42, 'rhoncus aliquet', 22);
insert into Planner (PlannerID, PlannerName, UserID) values (43, 'curae donec pharetra', 13);
insert into Planner (PlannerID, PlannerName, UserID) values (44, 'penatibus et', 2);
insert into Planner (PlannerID, PlannerName, UserID) values (45, 'sed accumsan', 20);
insert into Planner (PlannerID, PlannerName, UserID) values (46, 'faucibus', 6);
insert into Planner (PlannerID, PlannerName, UserID) values (47, 'rutrum nulla tellus', 34);
insert into Planner (PlannerID, PlannerName, UserID) values (48, 'nisl', 39);
insert into Planner (PlannerID, PlannerName, UserID) values (49, 'eu interdum', 18);
insert into Planner (PlannerID, PlannerName, UserID) values (50, 'ipsum', 36);
insert into Planner (PlannerID, PlannerName, UserID) values (51, 'quam', 35);
insert into Planner (PlannerID, PlannerName, UserID) values (52, 'ipsum', 40);
insert into Planner (PlannerID, PlannerName, UserID) values (53, 'morbi', 23);
insert into Planner (PlannerID, PlannerName, UserID) values (54, 'eu pede', 22);
insert into Planner (PlannerID, PlannerName, UserID) values (55, 'neque libero convallis', 8);
