use taskwiz;

insert into Calendar (CalendarID, CalendarName, UserID) values (1, 'velit nec', 32);
insert into Calendar (CalendarID, CalendarName, UserID) values (2, 'sem duis aliquam', 5);
insert into Calendar (CalendarID, CalendarName, UserID) values (3, 'in libero ut', 21);
insert into Calendar (CalendarID, CalendarName, UserID) values (4, 'pede posuere', 33);
insert into Calendar (CalendarID, CalendarName, UserID) values (5, 'integer', 24);
insert into Calendar (CalendarID, CalendarName, UserID) values (6, 'erat curabitur gravida', 32);
insert into Calendar (CalendarID, CalendarName, UserID) values (7, 'vestibulum', 10);
insert into Calendar (CalendarID, CalendarName, UserID) values (8, 'urna pretium', 29);
insert into Calendar (CalendarID, CalendarName, UserID) values (9, 'convallis', 23);
insert into Calendar (CalendarID, CalendarName, UserID) values (10, 'tincidunt', 35);
insert into Calendar (CalendarID, CalendarName, UserID) values (11, 'venenatis non', 12);
insert into Calendar (CalendarID, CalendarName, UserID) values (12, 'scelerisque mauris sit', 13);
insert into Calendar (CalendarID, CalendarName, UserID) values (13, 'convallis', 15);
insert into Calendar (CalendarID, CalendarName, UserID) values (14, 'mattis egestas metus', 12);
insert into Calendar (CalendarID, CalendarName, UserID) values (15, 'turpis nec', 9);
insert into Calendar (CalendarID, CalendarName, UserID) values (16, 'luctus rutrum', 22);
insert into Calendar (CalendarID, CalendarName, UserID) values (17, 'odio in hac', 35);
insert into Calendar (CalendarID, CalendarName, UserID) values (18, 'dapibus dolor vel', 38);
insert into Calendar (CalendarID, CalendarName, UserID) values (19, 'ullamcorper augue', 27);
insert into Calendar (CalendarID, CalendarName, UserID) values (20, 'id nisl venenatis', 13);
insert into Calendar (CalendarID, CalendarName, UserID) values (21, 'quam pharetra magna', 28);
insert into Calendar (CalendarID, CalendarName, UserID) values (22, 'turpis', 1);
insert into Calendar (CalendarID, CalendarName, UserID) values (23, 'enim in', 35);
insert into Calendar (CalendarID, CalendarName, UserID) values (24, 'amet diam', 29);
insert into Calendar (CalendarID, CalendarName, UserID) values (25, 'ipsum primis in', 37);
insert into Calendar (CalendarID, CalendarName, UserID) values (26, 'lorem ipsum dolor', 32);
insert into Calendar (CalendarID, CalendarName, UserID) values (27, 'sapien iaculis', 16);
insert into Calendar (CalendarID, CalendarName, UserID) values (28, 'malesuada in', 33);
insert into Calendar (CalendarID, CalendarName, UserID) values (29, 'ac', 36);
insert into Calendar (CalendarID, CalendarName, UserID) values (30, 'a', 20);
insert into Calendar (CalendarID, CalendarName, UserID) values (31, 'curabitur', 26);
insert into Calendar (CalendarID, CalendarName, UserID) values (32, 'diam erat', 16);
insert into Calendar (CalendarID, CalendarName, UserID) values (33, 'integer a', 15);
insert into Calendar (CalendarID, CalendarName, UserID) values (34, 'vulputate justo in', 18);
insert into Calendar (CalendarID, CalendarName, UserID) values (35, 'justo sit amet', 16);
insert into Calendar (CalendarID, CalendarName, UserID) values (36, 'lorem quisque ut', 29);
insert into Calendar (CalendarID, CalendarName, UserID) values (37, 'ac', 18);
insert into Calendar (CalendarID, CalendarName, UserID) values (38, 'hendrerit at', 21);
insert into Calendar (CalendarID, CalendarName, UserID) values (39, 'eget tincidunt', 29);
insert into Calendar (CalendarID, CalendarName, UserID) values (40, 'pede libero quis', 24);
insert into Calendar (CalendarID, CalendarName, UserID) values (41, 'mauris', 16);
insert into Calendar (CalendarID, CalendarName, UserID) values (42, 'morbi', 17);
insert into Calendar (CalendarID, CalendarName, UserID) values (43, 'ut', 6);
insert into Calendar (CalendarID, CalendarName, UserID) values (44, 'ipsum', 17);
insert into Calendar (CalendarID, CalendarName, UserID) values (45, 'nibh fusce', 34);
insert into Calendar (CalendarID, CalendarName, UserID) values (46, 'leo maecenas pulvinar', 8);
insert into Calendar (CalendarID, CalendarName, UserID) values (47, 'orci luctus', 24);
insert into Calendar (CalendarID, CalendarName, UserID) values (48, 'nisi eu orci', 31);
insert into Calendar (CalendarID, CalendarName, UserID) values (49, 'eget rutrum', 17);
insert into Calendar (CalendarID, CalendarName, UserID) values (50, 'quis', 14);
insert into Calendar (CalendarID, CalendarName, UserID) values (51, 'accumsan tellus', 29);
insert into Calendar (CalendarID, CalendarName, UserID) values (52, 'proin', 16);
insert into Calendar (CalendarID, CalendarName, UserID) values (53, 'mauris ullamcorper purus', 38);
insert into Calendar (CalendarID, CalendarName, UserID) values (54, 'ut dolor morbi', 28);
insert into Calendar (CalendarID, CalendarName, UserID) values (55, 'rhoncus mauris enim', 9);
