use taskwiz;

insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (1, 'Voyatouch', 18);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (2, 'Transcof', 19);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (3, 'Overhold', 4);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (4, 'Gembucket', 18);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (5, 'Fintone', 28);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (6, 'Alpha', 27);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (7, 'Tempsoft', 4);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (8, 'Job', 31);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (9, 'Flowdesk', 26);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (10, 'Y-find', 5);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (11, 'Y-find', 40);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (12, 'Hatity', 33);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (13, 'Vagram', 28);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (14, 'Sonsing', 35);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (15, 'Veribet', 4);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (16, 'Flexidy', 20);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (17, 'Sonair', 24);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (18, 'Bytecard', 18);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (19, 'Wrapsafe', 7);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (20, 'Vagram', 8);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (21, 'Namfix', 32);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (22, 'Zaam-Dox', 38);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (23, 'Pannier', 8);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (24, 'Toughjoyfax', 12);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (25, 'Tampflex', 21);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (26, 'Quo Lux', 40);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (27, 'Bitchip', 1);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (28, 'Matsoft', 4);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (29, 'Kanlam', 34);
insert into BudgetTracker (BudgetTrackerID, BudgetTrackerName, UserID) values (30, 'Redhold', 22);
